version: "3"

services:
  nav:
    build: .
    container_name: nav
    restart: always
    ports:
      - "8988:80" # Nginx端口
    volumes:
      - ./data:/data # 数据目录（包含数据库）
      - ./data/backups:/app/app/backups # 备份目录
      - ./data/uploads:/app/app/uploads # 上传文件目录
      - ./config/nginx:/etc/nginx/http.d # Nginx配置
    environment:
      - SECRET_KEY=change_this_to_a_secure_random_string
      - FLASK_ENV=production
